#include <exception>

#include <QtWidgets>
#include <QDebug>
#include <QString>
#include <QFile>
#include <QPixmap>
#include <QResizeEvent>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QIODevice>
#include <QMouseEvent>
#include <QPaintEvent>
#include <QSqlQuery>
#include <QSqlError>
#include <QMovie>
#include <QJsonDocument>
#include <QJsonArray>
#include <QJsonObject>
#include <QJsonValue>
#include <QUrl>
#include <QThread>
#include <QTimer>
#include <QCloseEvent>
#include <QSystemTrayIcon>
#include <QDir>
#include <QListWidgetItem>
#include <QListWidget>
#include <QCryptographicHash>
#include <QFile>
#include <QFileInfo>
#include <QPainter>
#include <QMimeData>
#include <QMutex>
#include <QScrollArea>
#include <QFrame>
#include <QWidget>
#include <QByteArray>

//自定义类型
#include "logic/GlobalParameter.h"
#include "logic/file/FileType.h"
#include "logic/network/Msg.h"