#include <exception>

#include <QtWidgets>
#include <QDebug>
#include <QString>
#include <QFile>
#include <QPixmap>
#include <QResizeEvent>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QIODevice>
#include <QMouseEvent>
#include <QPaintEvent>
#include <QSqlQuery>
#include <QSqlError>
#include <QMovie>
#include <QJsonDocument>
#include <QJsonArray>
#include <QJsonObject>
#include <QJsonValue>
#include <QUrl>